name: Update Firewall IP Threat Feeds

on:
  schedule:
    - cron: '0 * * * *'  # Runs automatically every hour
  workflow_dispatch:     # Allows manual trigger

permissions:
  contents: write        # Required to push the file back into main branch

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Request Modules
        run: pip install requests

      - name: Run IP Clean Script
        run: python clean_ips.py

      - name: Commit and Push File Directly to Main
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pa-master-ip-blocklist.txt
          git diff --quiet && git diff --cached --quiet || (git commit -m "Automated update of IP master blocklist" && git push origin HEAD:main)
